# Generated by Django 4.0.5 on 2022-07-25 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_profile_aadhar_number_alter_profile_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='closing_balance',
            field=models.IntegerField(null=True),
        ),
    ]
