# Generated by Django 4.0.5 on 2022-07-18 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Snippet',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='balance',
            new_name='closing_balance',
        ),
        migrations.AddField(
            model_name='profile',
            name='balance',
            field=models.IntegerField(null=True),
        ),
    ]
