# Generated by Django 4.0.5 on 2022-06-17 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0002_transactions_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercredentials',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='usercredentials',
            name='transaction',
        ),
        migrations.AddField(
            model_name='transactions',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.userprofile'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE,
                                       to='api.usercredentials'),
        ),
    ]
