# Generated by Django 4.0.5 on 2022-06-21 09:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0004_alter_transactions_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='Profile',
        ),
        migrations.RenameModel(
            old_name='UserCredentials',
            new_name='User',
        ),
    ]
